### ISSUE TITLE
Push to Chrome Web Store

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin-chrome-extension#1]
This extension is an attempt to revive the old firefox plugin, but it's written for Chrome instead of Firefox.

The main problem with the browser plugin was that it was difficult for developers to install. By publishing it to Chrome Web Store, developers will have the one-click-to-install experience, rather than having to clone the repository and build the plugin from source.

In order to publish the plugin, **we need a shared Google developer account**. (developers@zipkin.io?)
It might be enough that a few of the core Zipkin maintainers know its credentials.

I think the browser extensions will become a core part of the Zipkin experience, once they're actually easy to use!

**Comment by eirslett** [comment]
@adriancole I think you're the one who has access to DNS etc.? Which is needed to get a zipkin.io e-mail account?

**Comment by codefromthecrypt** [comment]
Yep Zoltan and I have access. I should be back online tomorrow and can look
into it.

**Comment by eirslett** [comment]
The extension is now hosted in the Chrome Web Store:

https://chrome.google.com/webstore/detail/zipkin-chrome-extension/jdpmaacocdhbmkppghmgnjmfikeeldfe

**Comment by codefromthecrypt** [comment]
https://twitter.com/zipkinproject/status/722919382590984193

**Comment by abesto** [comment]
Anything else to do here? Or can this be closed?

**Comment by eirslett** [comment]
Can be closed.
