### ISSUE TITLE
single-page app activity should be in the same trace, right?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-chrome-extension#5]
when tracing zipkin, I noticed that each request for the search page is in a different trace id. While this adds value (ex predictable trace ids), I suspect we'd get more if they were in the same trace. Is this feasible?

<img width="428" alt="screen shot 2016-04-13 at 10 04 54 am" src="https://cloud.githubusercontent.com/assets/64215/14495923/6abbceea-015f-11e6-8f4c-9ab646bec761.png">

**Comment by devinsba** [comment]
I think it might be valuable to be able to trace every call individually but also be able to from an application trigger some other logic. Consider the case of a page being open for hours with lots of short api calls creating a huge unwieldy trace view

**Comment by eirslett** [comment]
Try looking at http://m.finn.no/ on the network pane, leave it open for a minute, watch things going on... it's quite a circus! I don't really think it would make sense to collapse all these requests together into the same trace.
In the extreme case, you would have a single-page webapp without any site reloads at all. Then, 60 minutes of user activity would be collapsed into 1 single Zipkin trace. In my head, that doesn't sound quite right...

**Comment by codefromthecrypt** [comment]
I think it is probably best for the app to trace itself in order to collapse things like this. Once we have a javascript tracer, we could do this in zipkin-ui itself, for example.
